### ISSUE TITLE
As a new user, I want to create an account on HealthBridge so that I can access the platform to book medical appointments.

### ISSUE THREAD

**Issue by sindhureddykandada** [sindhureddykandada/HealthBridge#1]
Acceptance Criteria:

User can access a registration page
User can enter their personal information (name, email, password, etc.)
System validates the entered information
User is able to onboard and access the platform
Estimated Time - 1-2 weeks

**Comment by sindhureddykandada** [comment]
Acceptance Criteria:

- User can access a registration page
- User can enter their personal information (name, email, password, etc.)
- System validates the entered information
- User is able to onboard and access the platform

**Comment by chandrakanth98** [comment]
Acceptance Criteria Met, code has been pushed.
