### ISSUE TITLE
As a patient, I want to easily view all available doctors so that I can find the right doctor for my needs.

### ISSUE THREAD

**Issue by sindhureddykandada** [sindhureddykandada/HealthBridge#2]
Acceptance Criteria:

Patient dashboard has a tab to view doctors
Patient can access a page listing all available doctors
List includes doctor's name and specialization
Estimated time - 1-2 weeks

**Comment by sindhureddykandada** [comment]
Acceptance Criteria:

- Patient dashboard has a tab to view doctors
- Patient can access a page listing all available doctors
- List includes doctor's name and specialization

Estimated time - 1-2 weeks

**Comment by dinesh-reddy14** [comment]
The Acceptance Criteria is met, and code has been pushed.
